version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    volumes:
      - ./:/var/www/html

  ###> doctrine/doctrine-bundle ###
  database:
    container_name: postgres_vinyl
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - data_volume:/var/lib/postgresql/data/
      - pg_volume:/docker-entrypoint-initdb.d/:ro

  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:6.16"
    environment:
      POSTGRES_DB: app
      POSTGRES_HOST: postgres_vinyl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  ###> doctrine/doctrine-bundle ###
  data_volume:
  pg_volume:
###< doctrine/doctrine-bundle ###
